use_frameworks!

platform :ios, '10.0'

target 'ZZWNetworkWrapper_Example' do
  pod 'ZZWNetworkWrapper', :path => '../'

  target 'ZZWNetworkWrapper_Tests' do
    inherit! :search_paths

    
  end
end
